Removed the synchronization from singleton as I am pretty sure it did nothing. Changed the global screen object to final.
Moved ALL class and method lookup out of the callback for all platforms.  This should finally *FIX* the native null pointer errors causing JVM crashes when event delivery takes a longer than expected amount of time.  This will also further speed up the native event delivery.  The problem has something to do with JNI + Native threads causing a java.lang.NoClassDefFoundError error natively on a (*env)->FindClass if a separate call to (*env)->CallVoidMethod is still executing.  For example, a Button Down even is delivered to Java where some code takes several seconds to process the event.  If a Mouse Motion event occurs before the Button Down event completes (*env)->FindClass will return NULL.  I have absolutely no idea why this is happening.  I tried some synchronization both natively and in Java trying to create a lock on the screen and thus preventing simultaneous event deliveries without success.  The method currently implemented does not solve the underling issue however it should deliver events much faster and prevent null class lookups.  If anyone knows what the problem maybe please let me know.